
IMAGE_INSTALL_append = " \
    packagegroup-qt5-examples \
        qtbase-fonts \
	qt-framework-launcher \
	qt-omxh264enc-demo \
	demo-videos \
    mm-init \
    configuration \
    faac \
    gstreamer1.0-plugins-good-multifile \
    gstreamer1.0-plugins-good-jpeg \
    gstreamer1.0-plugins-good-icydemux \
    gstreamer1.0-plugins-base-apps \
    gstreamer1.0-plugins-base-app \
    gstreamer1.0-plugins-base-volume \
    gstreamer1.0-plugins-base-audiorate \
    gstreamer1.0-plugins-base-videorate \
    gstreamer1.0-plugins-base-encodebin \
    gstreamer1.0-plugins-base-vspmfilter \
    gstreamer1.0-plugins-bad-camerabin2 \
    gstreamer1.0-plugins-bad-faac \
	gstreamer1.0-plugins-bad-faad \
	gstreamer1.0-plugins-good-isomp4 \
"
